# Generated by Django 5.0.1 on 2024-02-02 18:12

import django.utils.timezone
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.CharField(blank=True, max_length=500)),
                ('updated_by', models.CharField(blank=True, max_length=500)),
                ('internal_id', users.models.ULIDField(editable=False, max_length=26, verbose_name='user_id')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('secondary_email', models.EmailField(help_text='secondary email address', max_length=254, verbose_name='secondary email')),
                ('first_name', models.CharField(help_text='First Name of the User', max_length=254, verbose_name='first name')),
                ('last_name', models.CharField(help_text='Last Name of the User', max_length=254, verbose_name='last name')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6, verbose_name='sex')),
                ('dob', models.DateTimeField(auto_now_add=True, verbose_name='date of birth')),
                ('employee_code', models.CharField(max_length=50, verbose_name='employee_code')),
                ('joining_date', models.DateTimeField(auto_now=True, verbose_name='joining date')),
                ('is_staff', models.BooleanField(default=False, verbose_name='is_staff')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.CharField(blank=True, max_length=500)),
                ('updated_by', models.CharField(blank=True, max_length=500)),
                ('internal_id', users.models.ULIDField(editable=False, max_length=26, verbose_name='address_id')),
                ('address_1', models.CharField(max_length=100, verbose_name='address_1')),
                ('address_2', models.CharField(max_length=100, verbose_name='address_2')),
                ('zip_code', models.CharField(max_length=50, verbose_name='zip_code')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.CharField(blank=True, max_length=500)),
                ('updated_by', models.CharField(blank=True, max_length=500)),
                ('internal_id', users.models.ULIDField(editable=False, max_length=26, verbose_name='role_id')),
                ('name', models.CharField(max_length=100, verbose_name='company_name')),
                ('branch', models.CharField(max_length=100, verbose_name='company_branch')),
            ],
            options={
                'verbose_name': 'Company',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.CharField(blank=True, max_length=500)),
                ('updated_by', models.CharField(blank=True, max_length=500)),
                ('internal_id', users.models.ULIDField(editable=False, max_length=26, verbose_name='country_ulid')),
                ('name', models.CharField(max_length=255, verbose_name='country_name')),
                ('isd_code', models.CharField(max_length=50, verbose_name='isd_code')),
                ('alpha2', models.CharField(max_length=100, verbose_name='alpha2')),
                ('alpha3', models.CharField(max_length=100, verbose_name='apha3')),
                ('currency', models.CharField(max_length=100, verbose_name='currency')),
                ('currency_symbol', models.CharField(max_length=100, verbose_name='currency_symbol')),
                ('currency_code', models.CharField(max_length=100, verbose_name='currency_code')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.CharField(blank=True, max_length=500)),
                ('updated_by', models.CharField(blank=True, max_length=500)),
                ('internal_id', users.models.ULIDField(editable=False, max_length=26, verbose_name='invitation_id')),
                ('first_name', models.CharField(max_length=254, verbose_name='first name')),
                ('last_name', models.CharField(max_length=254, verbose_name='last name')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Invitation',
                'verbose_name_plural': 'Invitations',
            },
        ),
        migrations.CreateModel(
            name='InvitationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.CharField(blank=True, max_length=500)),
                ('updated_by', models.CharField(blank=True, max_length=500)),
                ('internal_id', users.models.ULIDField(editable=False, max_length=26, verbose_name='invitation_id')),
                ('email', models.EmailField(max_length=255, verbose_name='email')),
                ('token', models.TextField()),
                ('expiry_date', models.DateTimeField(verbose_name='expires_at')),
            ],
            options={
                'verbose_name': 'Invitation History',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.CharField(blank=True, max_length=500)),
                ('updated_by', models.CharField(blank=True, max_length=500)),
                ('internal_id', users.models.ULIDField(editable=False, max_length=26, verbose_name='phone_ulid')),
                ('isd_code', models.CharField(verbose_name=models.CharField(blank=True, help_text='isd_code', verbose_name='isd_code'))),
                ('phone', models.CharField(verbose_name=models.CharField(blank=True, help_text='phone number', verbose_name='phone_number'))),
            ],
            options={
                'verbose_name': 'Phone Number',
                'verbose_name_plural': 'Phone Numbers',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.CharField(blank=True, max_length=500)),
                ('updated_by', models.CharField(blank=True, max_length=500)),
                ('internal_id', users.models.ULIDField(editable=False, max_length=26, verbose_name='role_id')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('name', models.CharField(max_length=100, verbose_name='role_name')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.CharField(blank=True, max_length=500)),
                ('updated_by', models.CharField(blank=True, max_length=500)),
                ('internal_id', users.models.ULIDField(editable=False, max_length=26, verbose_name='state_uuid')),
                ('name', models.CharField(max_length=255, verbose_name='city')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
            },
        ),
    ]
