# Generated by Django 5.0.1 on 2024-02-02 18:12

import django.db.models.deletion
import django.utils.timezone
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.CharField(blank=True, max_length=500)),
                ('updated_by', models.CharField(blank=True, max_length=500)),
                ('internal_id', users.models.ULIDField(editable=False, max_length=26, verbose_name='branding_file_id')),
                ('data', models.BinaryField()),
                ('filename', models.CharField(max_length=500)),
                ('file_size', models.CharField(max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.CharField(blank=True, max_length=500)),
                ('updated_by', models.CharField(blank=True, max_length=500)),
                ('internal_id', users.models.ULIDField(editable=False, max_length=26, verbose_name='domain_id')),
                ('tenant_id', models.CharField(max_length=500)),
                ('domain_name', models.CharField(max_length=500)),
                ('domain_type', models.CharField(choices=[('prefix', 'Prefix'), ('full', 'Full')], db_index=True, default='full', max_length=8)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.CharField(blank=True, max_length=500)),
                ('updated_by', models.CharField(blank=True, max_length=500)),
                ('internal_id', users.models.ULIDField(editable=False, max_length=26, verbose_name='tenant_id')),
                ('name', models.CharField(max_length=100, verbose_name='tenant_name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='tenant_slug')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.CharField(blank=True, max_length=500)),
                ('updated_by', models.CharField(blank=True, max_length=500)),
                ('internal_id', users.models.ULIDField(editable=False, max_length=26, verbose_name='tenant_id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenantTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.CharField(blank=True, max_length=500)),
                ('updated_by', models.CharField(blank=True, max_length=500)),
                ('internal_id', users.models.ULIDField(editable=False, max_length=26, verbose_name='tenant_theme_id')),
                ('primary_color', models.CharField(max_length=7, null=True)),
                ('secondary_color', models.CharField(max_length=7, null=True)),
                ('tertiary_color', models.CharField(max_length=7, null=True)),
                ('login_page_text', models.TextField(db_index=True, null=True)),
                ('brand_tagline', models.TextField(db_index=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DomainVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.CharField(blank=True, max_length=500)),
                ('updated_by', models.CharField(blank=True, max_length=500)),
                ('internal_id', users.models.ULIDField(editable=False, max_length=26, verbose_name='domain_verification_id')),
                ('tenant_id', models.CharField(max_length=500)),
                ('record', models.TextField(db_index=True, null=True)),
                ('record_type', models.CharField(choices=[('txt', 'TXT'), ('cname', 'CNAME')], db_index=True, default='txt', max_length=6)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.domain')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
