# Generated by Django 5.0.1 on 2024-02-02 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_config', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='tenanttheme',
            name='login_page_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theme_login_page_images', to='tenants.brandingfile'),
        ),
        migrations.AddField(
            model_name='tenanttheme',
            name='logo_main',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theme_logos_main', to='tenants.brandingfile'),
        ),
        migrations.AddField(
            model_name='tenanttheme',
            name='tenant_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_theme', to='tenants.tenant'),
        ),
    ]
