# Generated by Django 5.0.1 on 2024-02-02 18:12

import django.db.models.deletion
import django.utils.timezone
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leavetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.CharField(blank=True, max_length=500)),
                ('updated_by', models.CharField(blank=True, max_length=500)),
                ('internal_id', users.models.ULIDField(editable=False, max_length=26, verbose_name='leave_type_ulid')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='leave_name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='leave_slug')),
            ],
            options={
                'verbose_name': 'Leave Type',
                'verbose_name_plural': 'Leave Types',
            },
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.CharField(blank=True, max_length=500)),
                ('updated_by', models.CharField(blank=True, max_length=500)),
                ('internal_id', users.models.ULIDField(editable=False, max_length=26, verbose_name='timesheet_ulid')),
                ('project', models.CharField(max_length=100, unique=True, verbose_name='project')),
                ('task', models.CharField(max_length=100, unique=True, verbose_name='task')),
                ('date', models.DateField(null=True, verbose_name='date')),
                ('hours', models.FloatField(null=True, verbose_name='hours')),
            ],
            options={
                'verbose_name': 'Timesheet',
                'verbose_name_plural': 'Timesheets',
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.CharField(blank=True, max_length=500)),
                ('updated_by', models.CharField(blank=True, max_length=500)),
                ('internal_id', users.models.ULIDField(editable=False, max_length=26, verbose_name='leave_request_ulid')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=10, verbose_name='status')),
                ('start_date', models.DateTimeField(null=True, verbose_name='start_date')),
                ('end_date', models.DateTimeField(null=True, verbose_name='end_date')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='workflow.leavetype')),
            ],
            options={
                'verbose_name': 'Leave Request',
                'verbose_name_plural': 'Leave Requests',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.CharField(blank=True, max_length=500)),
                ('updated_by', models.CharField(blank=True, max_length=500)),
                ('internal_id', users.models.ULIDField(editable=False, max_length=26, verbose_name='attendance_ulid')),
                ('date', models.DateField(null=True, verbose_name='date')),
                ('day', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], verbose_name='day')),
                ('shift_code', models.CharField(blank=True, max_length=100, verbose_name='shift code')),
                ('in_time', models.TimeField(auto_now_add=True, null=True, verbose_name='in_time')),
                ('out_time', models.TimeField(auto_now_add=True, null=True, verbose_name='out_time')),
                ('total_hours', models.FloatField(null=True, verbose_name='total_hours')),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='workflow.timesheet')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.CharField(blank=True, max_length=500)),
                ('updated_by', models.CharField(blank=True, max_length=500)),
                ('internal_id', users.models.ULIDField(editable=False, max_length=26, verbose_name='leave_request_ulid')),
                ('balance', models.IntegerField(blank=True, verbose_name='leave_balance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='workflow.leavetype')),
            ],
            options={
                'verbose_name': 'Leave Balance',
                'verbose_name_plural': 'Leave Balances',
                'unique_together': {('user', 'leave_type')},
            },
        ),
    ]
